#pragma once

#define BUILD_CONFIG_DEBUG   1
#define BUILD_CONFIG_DIST    2
#define BUILD_CONFIG_RELEASE (BUILD_CONFIG_DEBUG | BUILD_CONFIG_DIST)

#define BUILD_ARCH_X86_64 1

#define BUILD_IS_CONFIG_DEBUG   (BUILD_CONFIG & BUILD_CONFIG_DEBUG)
#define BUILD_IS_CONFIG_RELEASE (BUILD_CONFIG == BUILD_CONFIG_RELEASE)
#define BUILD_IS_CONFIG_DIST    (BUILD_CONFIG & BUILD_CONFIG_DIST)

#define BUILD_IS_ARCH_X86_64 (BUILD_ARCH == BUILD_ARCH_X86_64)